theme: jekyll-theme-cayman
title: "PaintRL: Coverage Path Planning for Industrial Spray Painting with Reinforcement Learning"
description: "A framework that enables research on optimizing industrial spray painting for arbitrary objects with reinforcement learning"
