theme: jekyll-theme-cayman
title: "PaintRL: Coverage Path Planning for Industrial Spray Painting with Reinforcement Learning"
description: "A framework to optimize industrial spray painting for arbitrary objects with reinforcement learning"
